# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da511151ba7c060ad85fcb98f1e83c295a45550a3b6e0af25aed11266373f2f2c889b25f52450b20fb09fff4ec833db8ff48ce13ce089b224dfb608e03bc7953

test:
  secret_key_base: e1cd233145b9b3fa95245640f0e333ec21af12e3ec2e38a4c7d8e81edca37ae4cb1e273f99ef73b16dd18c9047116c366953c0cec7348fa490ff8a5977239e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
